extends Node2D

@export var player_token_scene: PackedScene = preload("res://scenes/player/PlayerToken.tscn")

@onready var board: Node2D = $Board
@onready var dice: Node2D = $Dice
@onready var roll_button: Button = $UI/RollButton
@onready var turn_label: Label = $UI/TurnLabel
@onready var state_machine: StateMachine = $StateMachine

var tokens: Array[Node2D] = []

# ---------------------------------------------------------------------------
# Character sprite paths — one SpriteFrames .tres per player (0-indexed).
# These files are generated by the AsepriteWizard editor dock:
#   1. Open the AsepriteWizard dock in Godot.
#   2. Import each charac{N}_walkFront.aseprite to produce a SpriteFrames .tres.
#   3. Save the output to the paths listed below.
# Until those .tres files exist, tokens fall back to a blank AnimatedSprite2D
# (no crash — just no visible sprite until baked).
# ---------------------------------------------------------------------------
const CHARACTER_SPRITE_FRAMES: Array[String] = [
	"res://assets/board_characters/character1/charac1_walkFront.tres",  # Player 1
	"res://assets/board_characters/character2/charac2_walkFront.tres",  # Player 2
	"res://assets/board_characters/character3/charac3_walkFront.tres",  # Player 3
	"res://assets/board_characters/character4/charac4_walkFront.tres",  # Player 4
]

func _ready() -> void:
	_spawn_tokens()
	roll_button.pressed.connect(_on_roll_pressed)
	EventBus.turn_started.connect(_on_turn_started)
	EventBus.player_moved.connect(_on_player_moved)
	# StateMachine auto-starts itself via call_deferred in its own _ready().
	# No need to call GameManager.start_turn() manually anymore — State_StartTurn does it.

func _spawn_tokens() -> void:
	for i in Constants.MAX_PLAYERS:
		var token: Node2D = player_token_scene.instantiate()
		add_child(token)

		# Assign the SpriteFrames resource before setup() so the
		# AnimatedSprite2D is populated when the animation is played.
		if i < CHARACTER_SPRITE_FRAMES.size():
			var frames_path: String = CHARACTER_SPRITE_FRAMES[i]
			if ResourceLoader.exists(frames_path):
				var frames := load(frames_path)
				if frames is SpriteFrames:
					token.sprite_frames = frames
				else:
					push_warning(
						"Game._spawn_tokens: '%s' is not a SpriteFrames resource." % frames_path
					)
			else:
				push_warning(
					"Game._spawn_tokens: SpriteFrames not found at '%s'. " % frames_path
					+ "Open AsepriteWizard and generate the .tres for character %d." % (i + 1)
				)

		token.setup(i, board)
		token.movement_finished.connect(_on_token_movement_finished)
		tokens.append(token)

func _on_token_movement_finished(player_index: int) -> void:
	EventBus.movement_finished.emit(player_index)

func _on_roll_pressed() -> void:
	# Guard now lives implicitly in State_WaitingForDice — it only listens
	# for dice_rolled while it's the active state, so a stray click while
	# in another state is harmless (dice.roll() just won't have a listener
	# waiting on EventBus.dice_rolled yet).
	dice.roll()

func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_accept"):
		_on_roll_pressed()

func _on_turn_started(player_index: int) -> void:
	var player_name: String = GameManager.players[player_index]["name"]
	turn_label.text = "%s's turn — roll the dice!" % player_name

func _on_player_moved(player_index: int, new_tile_index: int) -> void:
	# Tell the token to actually animate to its new tile.
	tokens[player_index].move_to(new_tile_index)
