# autoload/EventBus.gd
extends Node

@warning_ignore("unused_signal")
signal dice_rolled(player_index: int, result: int)
@warning_ignore("unused_signal")
signal player_moved(player_index: int, tile_index: int)
@warning_ignore("unused_signal")
signal tile_landed(player_index: int, tile_type: int)
@warning_ignore("unused_signal")
signal minigame_started(minigame_id: String)
@warning_ignore("unused_signal")
signal minigame_finished(scores: Dictionary)
@warning_ignore("unused_signal")
signal turn_started(player_index: int)
@warning_ignore("unused_signal")
signal game_over(winner_index: int)
@warning_ignore("unused_signal")
signal movement_finished(player_index: int)
@warning_ignore("unused_signal")
signal score_changed(player_index: int, new_score: int)
@warning_ignore("unused_signal")
signal trivia_started(question: String, options: Array, answering_player_idx: int)
@warning_ignore("unused_signal")
signal trivia_finished(scores: Dictionary)
